# Generated by Django 4.1 on 2022-09-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cinemaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/images/')),
                ('games_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games')),
            ],
        ),
    ]
